# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14bb4eac47469cb8e108e1ef05bc9f4bcc034b6437b40cb73752aee8bd15315be941bc803ec55bacdb9c0a0d4c454aa7f6649ae63658c83379d772b329e72d81
  twilio_account_sid: 'your Twilio Account SID'
  twilio_auth_token: 'Auth Token'

test:
  secret_key_base: d981b31b8b2835dfde95e5b41239e0e3991ad7527e69bfc26e81bf02d9644e5c626128e36243e1f33e7c98eb69f473847db2ac23e04406e8d24d2d400f0ac602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f28f5b56f6ff6b6ae16e90d27176ce73774219ce1b1a5a36cac5564d7e7d6f7c3bef7b6a7535766ebf788707d9acaf440edfd22530266e1f13f93d985ea995a4
   twilio_account_sid: 'your Twilio Account SID'
   twilio_auth_token: 'Auth Token'


